version: '3.4'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: APIGateways/nginx.Dockerfile
      
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
    
  discountdb:
    image: postgres
    
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge:latest    
    
  rabbitmq:
    image: rabbitmq:3-management-alpine 
    
  pgadmin:
    image: dpage/pgadmin4
    
  portainer:
    image: portainer/portainer-ce  

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      
  discount.api:
    image: ${DOCKER_REGISTRY-}discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
      
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile    
  
  #ocelotapigw:
  #  image: ${DOCKER_REGISTRY-}ocelotapigw
  #  build:
  #    context: .
  #    dockerfile: APIGateways/Ocelot.APIGateway/Dockerfile
      
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Infrastructure/microservices_eShopping.Identity/Dockerfile      
      
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: